"""Pinned economy values after the legally purchased early-game reserve."""

from __future__ import annotations

CERULEAN_RIVAL_POTION_RESERVE = 14
PEWTER_POKE_BALL_PURCHASE_QUANTITY = 9
PEWTER_POTION_PURCHASE_QUANTITY = 11
PEWTER_LOSS_POTION_PURCHASE_QUANTITY = PEWTER_POTION_PURCHASE_QUANTITY
PEWTER_POKE_BALL_PRICE = 200
PEWTER_POTION_PRICE = 300
PEWTER_TM34_SALE_PROCEEDS = 1_000
LAB_RIVAL_PRIZE_MONEY = 175
PEWTER_SUPPLY_WIN_STARTING_MONEY = 4_651
PEWTER_SUPPLY_LOSS_STARTING_MONEY = (
    PEWTER_SUPPLY_WIN_STARTING_MONEY - LAB_RIVAL_PRIZE_MONEY
)
PEWTER_SUPPLY_STARTING_MONEY = frozenset(
    {PEWTER_SUPPLY_WIN_STARTING_MONEY, PEWTER_SUPPLY_LOSS_STARTING_MONEY}
)
PEWTER_SUPPLY_COST = (
    PEWTER_POKE_BALL_PRICE * PEWTER_POKE_BALL_PURCHASE_QUANTITY
    + PEWTER_POTION_PRICE * PEWTER_POTION_PURCHASE_QUANTITY
)
PEWTER_LOSS_SUPPLY_COST = (
    PEWTER_POKE_BALL_PRICE * PEWTER_POKE_BALL_PURCHASE_QUANTITY
    + PEWTER_POTION_PRICE * PEWTER_LOSS_POTION_PURCHASE_QUANTITY
)
PEWTER_NET_SUPPLY_COST = PEWTER_SUPPLY_COST - PEWTER_TM34_SALE_PROCEEDS
PEWTER_LOSS_NET_SUPPLY_COST = PEWTER_LOSS_SUPPLY_COST - PEWTER_TM34_SALE_PROCEEDS

REVISED_ROUTE_REWARD_DELTA = 2
CERULEAN_EXTRA_POTION_QUANTITY = 3
CERULEAN_EXTRA_POTION_COST = PEWTER_POTION_PRICE * CERULEAN_EXTRA_POTION_QUANTITY
CERULEAN_STATUS_SUPPLY_COST = 400
CERULEAN_SUPPLY_COST = CERULEAN_EXTRA_POTION_COST + CERULEAN_STATUS_SUPPLY_COST
TUNNEL_STATUS_SUPPLY_COST = 200
TUNNEL_BALANCED_TEAM_RECOVERY_COST = 2_800
LAVENDER_TOP_UP_SUPPLY_COST = 5_800
CELADON_MONEY = (
    14_631
    - PEWTER_NET_SUPPLY_COST
    + REVISED_ROUTE_REWARD_DELTA
    - CERULEAN_SUPPLY_COST
    - TUNNEL_STATUS_SUPPLY_COST
    - TUNNEL_BALANCED_TEAM_RECOVERY_COST
    - LAVENDER_TOP_UP_SUPPLY_COST
)
LAVENDER_MONEY = CELADON_MONEY - 330
HIDEOUT_MONEY = (
    20_112
    - PEWTER_NET_SUPPLY_COST
    + REVISED_ROUTE_REWARD_DELTA
    - CERULEAN_SUPPLY_COST
    - TUNNEL_STATUS_SUPPLY_COST
    - TUNNEL_BALANCED_TEAM_RECOVERY_COST
    - LAVENDER_TOP_UP_SUPPLY_COST
)
TOWER_MONEY = (
    27_437
    - PEWTER_NET_SUPPLY_COST
    + REVISED_ROUTE_REWARD_DELTA
    - CERULEAN_SUPPLY_COST
    - TUNNEL_STATUS_SUPPLY_COST
    - TUNNEL_BALANCED_TEAM_RECOVERY_COST
    - LAVENDER_TOP_UP_SUPPLY_COST
)
FUCHSIA_MONEY = (
    30_137
    - PEWTER_NET_SUPPLY_COST
    + REVISED_ROUTE_REWARD_DELTA
    - CERULEAN_SUPPLY_COST
    - TUNNEL_STATUS_SUPPLY_COST
    - TUNNEL_BALANCED_TEAM_RECOVERY_COST
    - LAVENDER_TOP_UP_SUPPLY_COST
)
POST_SAFARI_MONEY = (
    29_637
    - PEWTER_NET_SUPPLY_COST
    + REVISED_ROUTE_REWARD_DELTA
    - CERULEAN_SUPPLY_COST
    - TUNNEL_STATUS_SUPPLY_COST
    - TUNNEL_BALANCED_TEAM_RECOVERY_COST
    - LAVENDER_TOP_UP_SUPPLY_COST
)
POST_KOGA_MONEY = (
    37_489
    - PEWTER_NET_SUPPLY_COST
    + REVISED_ROUTE_REWARD_DELTA
    - CERULEAN_SUPPLY_COST
    - TUNNEL_STATUS_SUPPLY_COST
    - TUNNEL_BALANCED_TEAM_RECOVERY_COST
    - LAVENDER_TOP_UP_SUPPLY_COST
)
POST_ERIKA_MONEY = (
    41_545
    - PEWTER_NET_SUPPLY_COST
    + REVISED_ROUTE_REWARD_DELTA
    - CERULEAN_SUPPLY_COST
    - TUNNEL_STATUS_SUPPLY_COST
    - TUNNEL_BALANCED_TEAM_RECOVERY_COST
    - LAVENDER_TOP_UP_SUPPLY_COST
)
POST_SAFFRON_PURCHASE_MONEY = (
    41_345
    - PEWTER_NET_SUPPLY_COST
    + REVISED_ROUTE_REWARD_DELTA
    - CERULEAN_SUPPLY_COST
    - TUNNEL_STATUS_SUPPLY_COST
    - TUNNEL_BALANCED_TEAM_RECOVERY_COST
    - LAVENDER_TOP_UP_SUPPLY_COST
)
POST_SILPH_MONEY = (
    41_594
    - PEWTER_NET_SUPPLY_COST
    + REVISED_ROUTE_REWARD_DELTA
    - CERULEAN_SUPPLY_COST
    - TUNNEL_STATUS_SUPPLY_COST
    - TUNNEL_BALANCED_TEAM_RECOVERY_COST
    - LAVENDER_TOP_UP_SUPPLY_COST
)

LAVENDER_SUPER_POTION_RESERVE = 12
HIDEOUT_SUPER_POTION_RESERVE = 6
TOWER_SUPER_POTION_RESERVE = 0
