from pokemon_red_completion.economy import (
    CERULEAN_EXTRA_POTION_COST,
    CERULEAN_RIVAL_POTION_RESERVE,
    CERULEAN_STATUS_SUPPLY_COST,
    CERULEAN_SUPPLY_COST,
    HIDEOUT_SUPER_POTION_RESERVE,
    LAB_RIVAL_PRIZE_MONEY,
    LAVENDER_MONEY,
    LAVENDER_SUPER_POTION_RESERVE,
    LAVENDER_TOP_UP_SUPPLY_COST,
    PEWTER_LOSS_NET_SUPPLY_COST,
    PEWTER_LOSS_POTION_PURCHASE_QUANTITY,
    PEWTER_LOSS_SUPPLY_COST,
    PEWTER_NET_SUPPLY_COST,
    PEWTER_POKE_BALL_PRICE,
    PEWTER_POKE_BALL_PURCHASE_QUANTITY,
    PEWTER_POTION_PRICE,
    PEWTER_POTION_PURCHASE_QUANTITY,
    PEWTER_SUPPLY_COST,
    PEWTER_SUPPLY_LOSS_STARTING_MONEY,
    PEWTER_SUPPLY_STARTING_MONEY,
    PEWTER_SUPPLY_WIN_STARTING_MONEY,
    PEWTER_TM34_SALE_PROCEEDS,
    TOWER_SUPER_POTION_RESERVE,
    TUNNEL_BALANCED_TEAM_RECOVERY_COST,
    TUNNEL_STATUS_SUPPLY_COST,
)


def test_pewter_purchase_builds_the_proven_rival_reserve() -> None:
    assert PEWTER_POKE_BALL_PURCHASE_QUANTITY == 9
    assert PEWTER_POTION_PURCHASE_QUANTITY == 11
    assert CERULEAN_RIVAL_POTION_RESERVE == 14
    assert PEWTER_SUPPLY_COST == (
        PEWTER_POKE_BALL_PRICE * PEWTER_POKE_BALL_PURCHASE_QUANTITY
        + PEWTER_POTION_PRICE * PEWTER_POTION_PURCHASE_QUANTITY
    )
    assert PEWTER_SUPPLY_COST == 5_100
    assert PEWTER_TM34_SALE_PROCEEDS == 1_000
    assert PEWTER_NET_SUPPLY_COST == 4_100
    assert PEWTER_LOSS_POTION_PURCHASE_QUANTITY == 11
    assert PEWTER_LOSS_SUPPLY_COST == 5_100
    assert PEWTER_LOSS_NET_SUPPLY_COST == 4_100
    assert LAB_RIVAL_PRIZE_MONEY == 175
    assert PEWTER_SUPPLY_WIN_STARTING_MONEY == 4_651
    assert PEWTER_SUPPLY_LOSS_STARTING_MONEY == 4_476
    assert frozenset({4_651, 4_476}) == PEWTER_SUPPLY_STARTING_MONEY


def test_revised_route_preserves_the_unused_lavender_recovery_reserve() -> None:
    assert CERULEAN_EXTRA_POTION_COST == 900
    assert CERULEAN_STATUS_SUPPLY_COST == 400
    assert CERULEAN_SUPPLY_COST == 1_300
    assert TUNNEL_STATUS_SUPPLY_COST == 200
    assert TUNNEL_BALANCED_TEAM_RECOVERY_COST == 2_800
    assert LAVENDER_TOP_UP_SUPPLY_COST == 5_800
    assert LAVENDER_MONEY == 103
    assert (
        LAVENDER_SUPER_POTION_RESERVE,
        HIDEOUT_SUPER_POTION_RESERVE,
        TOWER_SUPER_POTION_RESERVE,
    ) == (12, 6, 0)
